# Generated by Django 3.2.5 on 2021-07-28 12:06

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название контакта')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, verbose_name='Почта контакта')),
                ('number', models.CharField(max_length=30, verbose_name='Первый номер контакта')),
                ('number_two', models.CharField(max_length=30, null=True, verbose_name='Второй номер контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголово отзыва')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Текст отзыва')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='SightseeingAddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дополнительного элемента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SightseeingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=main.models.upload_location)),
                ('address', models.CharField(max_length=255, verbose_name='Адресс экскурсии')),
                ('number', models.CharField(max_length=255, verbose_name='номер экскурсии')),
                ('add_image', models.ImageField(upload_to=main.models.upload_location)),
                ('add_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sightseeingadditem', verbose_name='Элемент списка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NightGuide',
            fields=[
                ('sightseeingguide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.sightseeingguide')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.sightseeingguide',),
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=main.models.upload_location)),
                ('address', models.CharField(max_length=255, verbose_name='Адресс экскурсии')),
                ('number', models.CharField(max_length=255, verbose_name='номер экскурсии')),
                ('add_image', models.ImageField(upload_to=main.models.upload_location)),
                ('add_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sightseeingadditem', verbose_name='Элемент списка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
