# Generated by Django 3.2.5 on 2021-07-28 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('guests', models.CharField(max_length=1)),
                ('add_guests', models.CharField(max_length=1)),
                ('twin', models.BooleanField()),
                ('bathroom', models.CharField(max_length=32)),
                ('level', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('option', models.CharField(max_length=32, null=True)),
                ('category_id', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel')),
            ],
            options={
                'unique_together': {('number', 'category_id', 'hotel_id')},
            },
        ),
    ]
