# Generated by Django 3.2.5 on 2021-07-29 01:25

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210729_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название контакта букинга')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, verbose_name='Почта контакта')),
                ('number', models.CharField(max_length=30, verbose_name='Первый номер контакта')),
                ('number_two', models.CharField(max_length=30, null=True, verbose_name='Второй номер контакта')),
            ],
        ),
        migrations.CreateModel(
            name='GuideAddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дополнительного элемента')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'sightseeing_add_item',
                'verbose_name_plural': 'sightseeing_add_items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuseumAddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=main.models.upload_location)),
                ('address', models.CharField(max_length=255, verbose_name='Адресс экскурсии')),
                ('number', models.CharField(max_length=255, verbose_name='номер экскурсии')),
                ('add_image', models.ImageField(upload_to=main.models.upload_location)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NightGuideAddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дополнительного элемента')),
                ('slug', models.SlugField(unique=True)),
                ('sightseeing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sightseeingnightguide')),
            ],
            options={
                'verbose_name': 'sightseeing_add_item',
                'verbose_name_plural': 'sightseeing_add_items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название офера')),
                ('image', models.ImageField(upload_to='', verbose_name='фото офера')),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='ссыллка на видео с ютуба')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'room_image', 'verbose_name_plural': 'room_images'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'text', 'verbose_name_plural': 'texts'},
        ),
        migrations.RemoveField(
            model_name='sightseeingguide',
            name='add_items',
        ),
        migrations.RemoveField(
            model_name='sightseeingmuseum',
            name='add_items',
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголово отзыва'),
        ),
        migrations.DeleteModel(
            name='SightseeingAddItem',
        ),
        migrations.AddField(
            model_name='museumadditem',
            name='sightseeing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sightseeingmuseum'),
        ),
        migrations.AddField(
            model_name='guideadditem',
            name='sightseeing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.sightseeingguide'),
        ),
    ]
